services:
  backend:
    container_name: "transcribe-backend-container"
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    working_dir: /app
    ports:
      - ${BACKEND_PORT}
      - ${AIR_TOML_PORT}
    volumes:
      - "./backend:/app"
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      APP_ENV: dev
    stdin_open: true
    tty: true

  frontend:
    container_name: "transcribe-frontend-container"
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    working_dir: /app
    volumes:
      - "./frontend:/app"
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    tty: true
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    command: ${NEXT_PUBLIC_CMD}