[build]
cmd = "go build -o main ./cmd/server/main.go"
bin = "./main"
full_bin = "APP_ENV=dev ./main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
level = "debug"